// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	Ban             *ban
	Broadcast       *broadcast
	Donation        *donation
	Feedback        *feedback
	Message         *message
	Mode            *mode
	Personalization *personalization
	SelectedMode    *selectedMode
	Tariff          *tariff
	Usage           *usage
	User            *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Ban = &Q.Ban
	Broadcast = &Q.Broadcast
	Donation = &Q.Donation
	Feedback = &Q.Feedback
	Message = &Q.Message
	Mode = &Q.Mode
	Personalization = &Q.Personalization
	SelectedMode = &Q.SelectedMode
	Tariff = &Q.Tariff
	Usage = &Q.Usage
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Ban:             newBan(db, opts...),
		Broadcast:       newBroadcast(db, opts...),
		Donation:        newDonation(db, opts...),
		Feedback:        newFeedback(db, opts...),
		Message:         newMessage(db, opts...),
		Mode:            newMode(db, opts...),
		Personalization: newPersonalization(db, opts...),
		SelectedMode:    newSelectedMode(db, opts...),
		Tariff:          newTariff(db, opts...),
		Usage:           newUsage(db, opts...),
		User:            newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Ban             ban
	Broadcast       broadcast
	Donation        donation
	Feedback        feedback
	Message         message
	Mode            mode
	Personalization personalization
	SelectedMode    selectedMode
	Tariff          tariff
	Usage           usage
	User            user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Ban:             q.Ban.clone(db),
		Broadcast:       q.Broadcast.clone(db),
		Donation:        q.Donation.clone(db),
		Feedback:        q.Feedback.clone(db),
		Message:         q.Message.clone(db),
		Mode:            q.Mode.clone(db),
		Personalization: q.Personalization.clone(db),
		SelectedMode:    q.SelectedMode.clone(db),
		Tariff:          q.Tariff.clone(db),
		Usage:           q.Usage.clone(db),
		User:            q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Ban:             q.Ban.replaceDB(db),
		Broadcast:       q.Broadcast.replaceDB(db),
		Donation:        q.Donation.replaceDB(db),
		Feedback:        q.Feedback.replaceDB(db),
		Message:         q.Message.replaceDB(db),
		Mode:            q.Mode.replaceDB(db),
		Personalization: q.Personalization.replaceDB(db),
		SelectedMode:    q.SelectedMode.replaceDB(db),
		Tariff:          q.Tariff.replaceDB(db),
		Usage:           q.Usage.replaceDB(db),
		User:            q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Ban             IBanDo
	Broadcast       IBroadcastDo
	Donation        IDonationDo
	Feedback        IFeedbackDo
	Message         IMessageDo
	Mode            IModeDo
	Personalization IPersonalizationDo
	SelectedMode    ISelectedModeDo
	Tariff          ITariffDo
	Usage           IUsageDo
	User            IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Ban:             q.Ban.WithContext(ctx),
		Broadcast:       q.Broadcast.WithContext(ctx),
		Donation:        q.Donation.WithContext(ctx),
		Feedback:        q.Feedback.WithContext(ctx),
		Message:         q.Message.WithContext(ctx),
		Mode:            q.Mode.WithContext(ctx),
		Personalization: q.Personalization.WithContext(ctx),
		SelectedMode:    q.SelectedMode.WithContext(ctx),
		Tariff:          q.Tariff.WithContext(ctx),
		Usage:           q.Usage.WithContext(ctx),
		User:            q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
