// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ximanager/sources/persistence/entities"
)

func newBroadcast(db *gorm.DB, opts ...gen.DOOption) broadcast {
	_broadcast := broadcast{}

	_broadcast.broadcastDo.UseDB(db, opts...)
	_broadcast.broadcastDo.UseModel(&entities.Broadcast{})

	tableName := _broadcast.broadcastDo.TableName()
	_broadcast.ALL = field.NewAsterisk(tableName)
	_broadcast.ID = field.NewField(tableName, "id")
	_broadcast.UserID = field.NewField(tableName, "user_id")
	_broadcast.Text = field.NewString(tableName, "text")
	_broadcast.CreatedAt = field.NewTime(tableName, "created_at")
	_broadcast.User = broadcastHasOneUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "entities.User"),
		Messages: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Messages", "entities.Message"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Messages.User", "entities.User"),
			},
		},
		Donations: struct {
			field.RelationField
			UserEntity struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Donations", "entities.Donation"),
			UserEntity: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Donations.UserEntity", "entities.User"),
			},
		},
		CreatedModes: struct {
			field.RelationField
			Creator struct {
				field.RelationField
			}
			SelectedModes struct {
				field.RelationField
				Mode struct {
					field.RelationField
				}
				User struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("User.CreatedModes", "entities.Mode"),
			Creator: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.CreatedModes.Creator", "entities.User"),
			},
			SelectedModes: struct {
				field.RelationField
				Mode struct {
					field.RelationField
				}
				User struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("User.CreatedModes.SelectedModes", "entities.SelectedMode"),
				Mode: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.CreatedModes.SelectedModes.Mode", "entities.Mode"),
				},
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.CreatedModes.SelectedModes.User", "entities.User"),
				},
			},
		},
		SelectedModes: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.SelectedModes", "entities.SelectedMode"),
		},
		Personalizations: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Personalizations", "entities.Personalization"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Personalizations.User", "entities.User"),
			},
		},
		Usages: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Usages", "entities.Usage"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Usages.User", "entities.User"),
			},
		},
		Bans: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Bans", "entities.Ban"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Bans.User", "entities.User"),
			},
		},
	}

	_broadcast.fillFieldMap()

	return _broadcast
}

type broadcast struct {
	broadcastDo broadcastDo

	ALL       field.Asterisk
	ID        field.Field
	UserID    field.Field
	Text      field.String
	CreatedAt field.Time
	User      broadcastHasOneUser

	fieldMap map[string]field.Expr
}

func (b broadcast) Table(newTableName string) *broadcast {
	b.broadcastDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b broadcast) As(alias string) *broadcast {
	b.broadcastDo.DO = *(b.broadcastDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *broadcast) updateTableName(table string) *broadcast {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewField(table, "id")
	b.UserID = field.NewField(table, "user_id")
	b.Text = field.NewString(table, "text")
	b.CreatedAt = field.NewTime(table, "created_at")

	b.fillFieldMap()

	return b
}

func (b *broadcast) WithContext(ctx context.Context) IBroadcastDo {
	return b.broadcastDo.WithContext(ctx)
}

func (b broadcast) TableName() string { return b.broadcastDo.TableName() }

func (b broadcast) Alias() string { return b.broadcastDo.Alias() }

func (b broadcast) Columns(cols ...field.Expr) gen.Columns { return b.broadcastDo.Columns(cols...) }

func (b *broadcast) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *broadcast) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 5)
	b.fieldMap["id"] = b.ID
	b.fieldMap["user_id"] = b.UserID
	b.fieldMap["text"] = b.Text
	b.fieldMap["created_at"] = b.CreatedAt

}

func (b broadcast) clone(db *gorm.DB) broadcast {
	b.broadcastDo.ReplaceConnPool(db.Statement.ConnPool)
	b.User.db = db.Session(&gorm.Session{Initialized: true})
	b.User.db.Statement.ConnPool = db.Statement.ConnPool
	return b
}

func (b broadcast) replaceDB(db *gorm.DB) broadcast {
	b.broadcastDo.ReplaceDB(db)
	b.User.db = db.Session(&gorm.Session{})
	return b
}

type broadcastHasOneUser struct {
	db *gorm.DB

	field.RelationField

	Messages struct {
		field.RelationField
		User struct {
			field.RelationField
		}
	}
	Donations struct {
		field.RelationField
		UserEntity struct {
			field.RelationField
		}
	}
	CreatedModes struct {
		field.RelationField
		Creator struct {
			field.RelationField
		}
		SelectedModes struct {
			field.RelationField
			Mode struct {
				field.RelationField
			}
			User struct {
				field.RelationField
			}
		}
	}
	SelectedModes struct {
		field.RelationField
	}
	Personalizations struct {
		field.RelationField
		User struct {
			field.RelationField
		}
	}
	Usages struct {
		field.RelationField
		User struct {
			field.RelationField
		}
	}
	Bans struct {
		field.RelationField
		User struct {
			field.RelationField
		}
	}
}

func (a broadcastHasOneUser) Where(conds ...field.Expr) *broadcastHasOneUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a broadcastHasOneUser) WithContext(ctx context.Context) *broadcastHasOneUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a broadcastHasOneUser) Session(session *gorm.Session) *broadcastHasOneUser {
	a.db = a.db.Session(session)
	return &a
}

func (a broadcastHasOneUser) Model(m *entities.Broadcast) *broadcastHasOneUserTx {
	return &broadcastHasOneUserTx{a.db.Model(m).Association(a.Name())}
}

func (a broadcastHasOneUser) Unscoped() *broadcastHasOneUser {
	a.db = a.db.Unscoped()
	return &a
}

type broadcastHasOneUserTx struct{ tx *gorm.Association }

func (a broadcastHasOneUserTx) Find() (result *entities.User, err error) {
	return result, a.tx.Find(&result)
}

func (a broadcastHasOneUserTx) Append(values ...*entities.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a broadcastHasOneUserTx) Replace(values ...*entities.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a broadcastHasOneUserTx) Delete(values ...*entities.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a broadcastHasOneUserTx) Clear() error {
	return a.tx.Clear()
}

func (a broadcastHasOneUserTx) Count() int64 {
	return a.tx.Count()
}

func (a broadcastHasOneUserTx) Unscoped() *broadcastHasOneUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type broadcastDo struct{ gen.DO }

type IBroadcastDo interface {
	gen.SubQuery
	Debug() IBroadcastDo
	WithContext(ctx context.Context) IBroadcastDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBroadcastDo
	WriteDB() IBroadcastDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBroadcastDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBroadcastDo
	Not(conds ...gen.Condition) IBroadcastDo
	Or(conds ...gen.Condition) IBroadcastDo
	Select(conds ...field.Expr) IBroadcastDo
	Where(conds ...gen.Condition) IBroadcastDo
	Order(conds ...field.Expr) IBroadcastDo
	Distinct(cols ...field.Expr) IBroadcastDo
	Omit(cols ...field.Expr) IBroadcastDo
	Join(table schema.Tabler, on ...field.Expr) IBroadcastDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBroadcastDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBroadcastDo
	Group(cols ...field.Expr) IBroadcastDo
	Having(conds ...gen.Condition) IBroadcastDo
	Limit(limit int) IBroadcastDo
	Offset(offset int) IBroadcastDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBroadcastDo
	Unscoped() IBroadcastDo
	Create(values ...*entities.Broadcast) error
	CreateInBatches(values []*entities.Broadcast, batchSize int) error
	Save(values ...*entities.Broadcast) error
	First() (*entities.Broadcast, error)
	Take() (*entities.Broadcast, error)
	Last() (*entities.Broadcast, error)
	Find() ([]*entities.Broadcast, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entities.Broadcast, err error)
	FindInBatches(result *[]*entities.Broadcast, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entities.Broadcast) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBroadcastDo
	Assign(attrs ...field.AssignExpr) IBroadcastDo
	Joins(fields ...field.RelationField) IBroadcastDo
	Preload(fields ...field.RelationField) IBroadcastDo
	FirstOrInit() (*entities.Broadcast, error)
	FirstOrCreate() (*entities.Broadcast, error)
	FindByPage(offset int, limit int) (result []*entities.Broadcast, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBroadcastDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b broadcastDo) Debug() IBroadcastDo {
	return b.withDO(b.DO.Debug())
}

func (b broadcastDo) WithContext(ctx context.Context) IBroadcastDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b broadcastDo) ReadDB() IBroadcastDo {
	return b.Clauses(dbresolver.Read)
}

func (b broadcastDo) WriteDB() IBroadcastDo {
	return b.Clauses(dbresolver.Write)
}

func (b broadcastDo) Session(config *gorm.Session) IBroadcastDo {
	return b.withDO(b.DO.Session(config))
}

func (b broadcastDo) Clauses(conds ...clause.Expression) IBroadcastDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b broadcastDo) Returning(value interface{}, columns ...string) IBroadcastDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b broadcastDo) Not(conds ...gen.Condition) IBroadcastDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b broadcastDo) Or(conds ...gen.Condition) IBroadcastDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b broadcastDo) Select(conds ...field.Expr) IBroadcastDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b broadcastDo) Where(conds ...gen.Condition) IBroadcastDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b broadcastDo) Order(conds ...field.Expr) IBroadcastDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b broadcastDo) Distinct(cols ...field.Expr) IBroadcastDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b broadcastDo) Omit(cols ...field.Expr) IBroadcastDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b broadcastDo) Join(table schema.Tabler, on ...field.Expr) IBroadcastDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b broadcastDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBroadcastDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b broadcastDo) RightJoin(table schema.Tabler, on ...field.Expr) IBroadcastDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b broadcastDo) Group(cols ...field.Expr) IBroadcastDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b broadcastDo) Having(conds ...gen.Condition) IBroadcastDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b broadcastDo) Limit(limit int) IBroadcastDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b broadcastDo) Offset(offset int) IBroadcastDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b broadcastDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBroadcastDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b broadcastDo) Unscoped() IBroadcastDo {
	return b.withDO(b.DO.Unscoped())
}

func (b broadcastDo) Create(values ...*entities.Broadcast) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b broadcastDo) CreateInBatches(values []*entities.Broadcast, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b broadcastDo) Save(values ...*entities.Broadcast) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b broadcastDo) First() (*entities.Broadcast, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Broadcast), nil
	}
}

func (b broadcastDo) Take() (*entities.Broadcast, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Broadcast), nil
	}
}

func (b broadcastDo) Last() (*entities.Broadcast, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Broadcast), nil
	}
}

func (b broadcastDo) Find() ([]*entities.Broadcast, error) {
	result, err := b.DO.Find()
	return result.([]*entities.Broadcast), err
}

func (b broadcastDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entities.Broadcast, err error) {
	buf := make([]*entities.Broadcast, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b broadcastDo) FindInBatches(result *[]*entities.Broadcast, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b broadcastDo) Attrs(attrs ...field.AssignExpr) IBroadcastDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b broadcastDo) Assign(attrs ...field.AssignExpr) IBroadcastDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b broadcastDo) Joins(fields ...field.RelationField) IBroadcastDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b broadcastDo) Preload(fields ...field.RelationField) IBroadcastDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b broadcastDo) FirstOrInit() (*entities.Broadcast, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Broadcast), nil
	}
}

func (b broadcastDo) FirstOrCreate() (*entities.Broadcast, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Broadcast), nil
	}
}

func (b broadcastDo) FindByPage(offset int, limit int) (result []*entities.Broadcast, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b broadcastDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b broadcastDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b broadcastDo) Delete(models ...*entities.Broadcast) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *broadcastDo) withDO(do gen.Dao) *broadcastDo {
	b.DO = *do.(*gen.DO)
	return b
}
