// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ximanager/sources/persistence/entities"
)

func newTariff(db *gorm.DB, opts ...gen.DOOption) tariff {
	_tariff := tariff{}

	_tariff.tariffDo.UseDB(db, opts...)
	_tariff.tariffDo.UseModel(&entities.Tariff{})

	tableName := _tariff.tariffDo.TableName()
	_tariff.ALL = field.NewAsterisk(tableName)
	_tariff.ID = field.NewInt64(tableName, "id")
	_tariff.Key = field.NewString(tableName, "key")
	_tariff.DisplayName = field.NewString(tableName, "display_name")
	_tariff.CreatedAt = field.NewTime(tableName, "created_at")
	_tariff.DialerModels = field.NewBytes(tableName, "dialer_models")
	_tariff.DialerReasoningEffort = field.NewString(tableName, "dialer_reasoning_effort")
	_tariff.VisionPrimaryModel = field.NewString(tableName, "vision_primary_model")
	_tariff.VisionFallbackModels = field.NewField(tableName, "vision_fallback_models")
	_tariff.ContextTTLSeconds = field.NewInt(tableName, "context_ttl_seconds")
	_tariff.ContextMaxMessages = field.NewInt(tableName, "context_max_messages")
	_tariff.ContextMaxTokens = field.NewInt(tableName, "context_max_tokens")
	_tariff.UsageVisionDaily = field.NewInt(tableName, "usage_vision_daily")
	_tariff.UsageVisionMonthly = field.NewInt(tableName, "usage_vision_monthly")
	_tariff.UsageDialerDaily = field.NewInt(tableName, "usage_dialer_daily")
	_tariff.UsageDialerMonthly = field.NewInt(tableName, "usage_dialer_monthly")
	_tariff.UsageWhisperDaily = field.NewInt(tableName, "usage_whisper_daily")
	_tariff.UsageWhisperMonthly = field.NewInt(tableName, "usage_whisper_monthly")
	_tariff.SpendingDailyLimit = field.NewField(tableName, "spending_daily_limit")
	_tariff.SpendingMonthlyLimit = field.NewField(tableName, "spending_monthly_limit")

	_tariff.fillFieldMap()

	return _tariff
}

type tariff struct {
	tariffDo tariffDo

	ALL                   field.Asterisk
	ID                    field.Int64
	Key                   field.String
	DisplayName           field.String
	CreatedAt             field.Time
	DialerModels          field.Bytes
	DialerReasoningEffort field.String
	VisionPrimaryModel    field.String
	VisionFallbackModels  field.Field
	ContextTTLSeconds     field.Int
	ContextMaxMessages    field.Int
	ContextMaxTokens      field.Int
	UsageVisionDaily      field.Int
	UsageVisionMonthly    field.Int
	UsageDialerDaily      field.Int
	UsageDialerMonthly    field.Int
	UsageWhisperDaily     field.Int
	UsageWhisperMonthly   field.Int
	SpendingDailyLimit    field.Field
	SpendingMonthlyLimit  field.Field

	fieldMap map[string]field.Expr
}

func (t tariff) Table(newTableName string) *tariff {
	t.tariffDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tariff) As(alias string) *tariff {
	t.tariffDo.DO = *(t.tariffDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tariff) updateTableName(table string) *tariff {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.Key = field.NewString(table, "key")
	t.DisplayName = field.NewString(table, "display_name")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.DialerModels = field.NewBytes(table, "dialer_models")
	t.DialerReasoningEffort = field.NewString(table, "dialer_reasoning_effort")
	t.VisionPrimaryModel = field.NewString(table, "vision_primary_model")
	t.VisionFallbackModels = field.NewField(table, "vision_fallback_models")
	t.ContextTTLSeconds = field.NewInt(table, "context_ttl_seconds")
	t.ContextMaxMessages = field.NewInt(table, "context_max_messages")
	t.ContextMaxTokens = field.NewInt(table, "context_max_tokens")
	t.UsageVisionDaily = field.NewInt(table, "usage_vision_daily")
	t.UsageVisionMonthly = field.NewInt(table, "usage_vision_monthly")
	t.UsageDialerDaily = field.NewInt(table, "usage_dialer_daily")
	t.UsageDialerMonthly = field.NewInt(table, "usage_dialer_monthly")
	t.UsageWhisperDaily = field.NewInt(table, "usage_whisper_daily")
	t.UsageWhisperMonthly = field.NewInt(table, "usage_whisper_monthly")
	t.SpendingDailyLimit = field.NewField(table, "spending_daily_limit")
	t.SpendingMonthlyLimit = field.NewField(table, "spending_monthly_limit")

	t.fillFieldMap()

	return t
}

func (t *tariff) WithContext(ctx context.Context) ITariffDo { return t.tariffDo.WithContext(ctx) }

func (t tariff) TableName() string { return t.tariffDo.TableName() }

func (t tariff) Alias() string { return t.tariffDo.Alias() }

func (t tariff) Columns(cols ...field.Expr) gen.Columns { return t.tariffDo.Columns(cols...) }

func (t *tariff) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tariff) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 19)
	t.fieldMap["id"] = t.ID
	t.fieldMap["key"] = t.Key
	t.fieldMap["display_name"] = t.DisplayName
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["dialer_models"] = t.DialerModels
	t.fieldMap["dialer_reasoning_effort"] = t.DialerReasoningEffort
	t.fieldMap["vision_primary_model"] = t.VisionPrimaryModel
	t.fieldMap["vision_fallback_models"] = t.VisionFallbackModels
	t.fieldMap["context_ttl_seconds"] = t.ContextTTLSeconds
	t.fieldMap["context_max_messages"] = t.ContextMaxMessages
	t.fieldMap["context_max_tokens"] = t.ContextMaxTokens
	t.fieldMap["usage_vision_daily"] = t.UsageVisionDaily
	t.fieldMap["usage_vision_monthly"] = t.UsageVisionMonthly
	t.fieldMap["usage_dialer_daily"] = t.UsageDialerDaily
	t.fieldMap["usage_dialer_monthly"] = t.UsageDialerMonthly
	t.fieldMap["usage_whisper_daily"] = t.UsageWhisperDaily
	t.fieldMap["usage_whisper_monthly"] = t.UsageWhisperMonthly
	t.fieldMap["spending_daily_limit"] = t.SpendingDailyLimit
	t.fieldMap["spending_monthly_limit"] = t.SpendingMonthlyLimit
}

func (t tariff) clone(db *gorm.DB) tariff {
	t.tariffDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tariff) replaceDB(db *gorm.DB) tariff {
	t.tariffDo.ReplaceDB(db)
	return t
}

type tariffDo struct{ gen.DO }

type ITariffDo interface {
	gen.SubQuery
	Debug() ITariffDo
	WithContext(ctx context.Context) ITariffDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITariffDo
	WriteDB() ITariffDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITariffDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITariffDo
	Not(conds ...gen.Condition) ITariffDo
	Or(conds ...gen.Condition) ITariffDo
	Select(conds ...field.Expr) ITariffDo
	Where(conds ...gen.Condition) ITariffDo
	Order(conds ...field.Expr) ITariffDo
	Distinct(cols ...field.Expr) ITariffDo
	Omit(cols ...field.Expr) ITariffDo
	Join(table schema.Tabler, on ...field.Expr) ITariffDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITariffDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITariffDo
	Group(cols ...field.Expr) ITariffDo
	Having(conds ...gen.Condition) ITariffDo
	Limit(limit int) ITariffDo
	Offset(offset int) ITariffDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITariffDo
	Unscoped() ITariffDo
	Create(values ...*entities.Tariff) error
	CreateInBatches(values []*entities.Tariff, batchSize int) error
	Save(values ...*entities.Tariff) error
	First() (*entities.Tariff, error)
	Take() (*entities.Tariff, error)
	Last() (*entities.Tariff, error)
	Find() ([]*entities.Tariff, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entities.Tariff, err error)
	FindInBatches(result *[]*entities.Tariff, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entities.Tariff) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITariffDo
	Assign(attrs ...field.AssignExpr) ITariffDo
	Joins(fields ...field.RelationField) ITariffDo
	Preload(fields ...field.RelationField) ITariffDo
	FirstOrInit() (*entities.Tariff, error)
	FirstOrCreate() (*entities.Tariff, error)
	FindByPage(offset int, limit int) (result []*entities.Tariff, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITariffDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tariffDo) Debug() ITariffDo {
	return t.withDO(t.DO.Debug())
}

func (t tariffDo) WithContext(ctx context.Context) ITariffDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tariffDo) ReadDB() ITariffDo {
	return t.Clauses(dbresolver.Read)
}

func (t tariffDo) WriteDB() ITariffDo {
	return t.Clauses(dbresolver.Write)
}

func (t tariffDo) Session(config *gorm.Session) ITariffDo {
	return t.withDO(t.DO.Session(config))
}

func (t tariffDo) Clauses(conds ...clause.Expression) ITariffDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tariffDo) Returning(value interface{}, columns ...string) ITariffDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tariffDo) Not(conds ...gen.Condition) ITariffDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tariffDo) Or(conds ...gen.Condition) ITariffDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tariffDo) Select(conds ...field.Expr) ITariffDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tariffDo) Where(conds ...gen.Condition) ITariffDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tariffDo) Order(conds ...field.Expr) ITariffDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tariffDo) Distinct(cols ...field.Expr) ITariffDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tariffDo) Omit(cols ...field.Expr) ITariffDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tariffDo) Join(table schema.Tabler, on ...field.Expr) ITariffDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tariffDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITariffDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tariffDo) RightJoin(table schema.Tabler, on ...field.Expr) ITariffDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tariffDo) Group(cols ...field.Expr) ITariffDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tariffDo) Having(conds ...gen.Condition) ITariffDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tariffDo) Limit(limit int) ITariffDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tariffDo) Offset(offset int) ITariffDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tariffDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITariffDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tariffDo) Unscoped() ITariffDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tariffDo) Create(values ...*entities.Tariff) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tariffDo) CreateInBatches(values []*entities.Tariff, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tariffDo) Save(values ...*entities.Tariff) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tariffDo) First() (*entities.Tariff, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Tariff), nil
	}
}

func (t tariffDo) Take() (*entities.Tariff, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Tariff), nil
	}
}

func (t tariffDo) Last() (*entities.Tariff, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Tariff), nil
	}
}

func (t tariffDo) Find() ([]*entities.Tariff, error) {
	result, err := t.DO.Find()
	return result.([]*entities.Tariff), err
}

func (t tariffDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entities.Tariff, err error) {
	buf := make([]*entities.Tariff, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tariffDo) FindInBatches(result *[]*entities.Tariff, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tariffDo) Attrs(attrs ...field.AssignExpr) ITariffDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tariffDo) Assign(attrs ...field.AssignExpr) ITariffDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tariffDo) Joins(fields ...field.RelationField) ITariffDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tariffDo) Preload(fields ...field.RelationField) ITariffDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tariffDo) FirstOrInit() (*entities.Tariff, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Tariff), nil
	}
}

func (t tariffDo) FirstOrCreate() (*entities.Tariff, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entities.Tariff), nil
	}
}

func (t tariffDo) FindByPage(offset int, limit int) (result []*entities.Tariff, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tariffDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tariffDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tariffDo) Delete(models ...*entities.Tariff) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tariffDo) withDO(do gen.Dao) *tariffDo {
	t.DO = *do.(*gen.DO)
	return t
}
