// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ximanager/sources/persistence/entities"
)

func newUser(db *gorm.DB, opts ...gen.DOOption) user {
	_user := user{}

	_user.userDo.UseDB(db, opts...)
	_user.userDo.UseModel(&entities.User{})

	tableName := _user.userDo.TableName()
	_user.ALL = field.NewAsterisk(tableName)
	_user.ID = field.NewField(tableName, "id")
	_user.UserID = field.NewInt64(tableName, "user_id")
	_user.Username = field.NewString(tableName, "username")
	_user.Fullname = field.NewString(tableName, "fullname")
	_user.Rights = field.NewField(tableName, "rights")
	_user.IsActive = field.NewBool(tableName, "is_active")
	_user.IsStackAllowed = field.NewBool(tableName, "is_stack_allowed")
	_user.WindowLimit = field.NewInt64(tableName, "window_limit")
	_user.CreatedAt = field.NewTime(tableName, "created_at")
	_user.Messages = userHasManyMessages{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Messages", "entities.Message"),
		User: struct {
			field.RelationField
			Messages struct {
				field.RelationField
			}
			Donations struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}
			CreatedModes struct {
				field.RelationField
				Creator struct {
					field.RelationField
				}
				SelectedModes struct {
					field.RelationField
					Mode struct {
						field.RelationField
					}
					User struct {
						field.RelationField
					}
				}
			}
			SelectedModes struct {
				field.RelationField
			}
			Pins struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Messages.User", "entities.User"),
			Messages: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Messages.User.Messages", "entities.Message"),
			},
			Donations: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Messages.User.Donations", "entities.Donation"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Messages.User.Donations.User", "entities.User"),
				},
			},
			CreatedModes: struct {
				field.RelationField
				Creator struct {
					field.RelationField
				}
				SelectedModes struct {
					field.RelationField
					Mode struct {
						field.RelationField
					}
					User struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Messages.User.CreatedModes", "entities.Mode"),
				Creator: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Messages.User.CreatedModes.Creator", "entities.User"),
				},
				SelectedModes: struct {
					field.RelationField
					Mode struct {
						field.RelationField
					}
					User struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Messages.User.CreatedModes.SelectedModes", "entities.SelectedMode"),
					Mode: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Messages.User.CreatedModes.SelectedModes.Mode", "entities.Mode"),
					},
					User: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Messages.User.CreatedModes.SelectedModes.User", "entities.User"),
					},
				},
			},
			SelectedModes: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Messages.User.SelectedModes", "entities.SelectedMode"),
			},
			Pins: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Messages.User.Pins", "entities.Pin"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Messages.User.Pins.User", "entities.User"),
				},
			},
		},
	}

	_user.Donations = userHasManyDonations{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Donations", "entities.Donation"),
	}

	_user.CreatedModes = userHasManyCreatedModes{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("CreatedModes", "entities.Mode"),
	}

	_user.SelectedModes = userHasManySelectedModes{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SelectedModes", "entities.SelectedMode"),
	}

	_user.Pins = userHasManyPins{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Pins", "entities.Pin"),
	}

	_user.fillFieldMap()

	return _user
}

type user struct {
	userDo userDo

	ALL            field.Asterisk
	ID             field.Field
	UserID         field.Int64
	Username       field.String
	Fullname       field.String
	Rights         field.Field
	IsActive       field.Bool
	IsStackAllowed field.Bool
	WindowLimit    field.Int64
	CreatedAt      field.Time
	Messages       userHasManyMessages

	Donations userHasManyDonations

	CreatedModes userHasManyCreatedModes

	SelectedModes userHasManySelectedModes

	Pins userHasManyPins

	fieldMap map[string]field.Expr
}

func (u user) Table(newTableName string) *user {
	u.userDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u user) As(alias string) *user {
	u.userDo.DO = *(u.userDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *user) updateTableName(table string) *user {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewField(table, "id")
	u.UserID = field.NewInt64(table, "user_id")
	u.Username = field.NewString(table, "username")
	u.Fullname = field.NewString(table, "fullname")
	u.Rights = field.NewField(table, "rights")
	u.IsActive = field.NewBool(table, "is_active")
	u.IsStackAllowed = field.NewBool(table, "is_stack_allowed")
	u.WindowLimit = field.NewInt64(table, "window_limit")
	u.CreatedAt = field.NewTime(table, "created_at")

	u.fillFieldMap()

	return u
}

func (u *user) WithContext(ctx context.Context) IUserDo { return u.userDo.WithContext(ctx) }

func (u user) TableName() string { return u.userDo.TableName() }

func (u user) Alias() string { return u.userDo.Alias() }

func (u user) Columns(cols ...field.Expr) gen.Columns { return u.userDo.Columns(cols...) }

func (u *user) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *user) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 14)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["username"] = u.Username
	u.fieldMap["fullname"] = u.Fullname
	u.fieldMap["rights"] = u.Rights
	u.fieldMap["is_active"] = u.IsActive
	u.fieldMap["is_stack_allowed"] = u.IsStackAllowed
	u.fieldMap["window_limit"] = u.WindowLimit
	u.fieldMap["created_at"] = u.CreatedAt

}

func (u user) clone(db *gorm.DB) user {
	u.userDo.ReplaceConnPool(db.Statement.ConnPool)
	u.Messages.db = db.Session(&gorm.Session{Initialized: true})
	u.Messages.db.Statement.ConnPool = db.Statement.ConnPool
	u.Donations.db = db.Session(&gorm.Session{Initialized: true})
	u.Donations.db.Statement.ConnPool = db.Statement.ConnPool
	u.CreatedModes.db = db.Session(&gorm.Session{Initialized: true})
	u.CreatedModes.db.Statement.ConnPool = db.Statement.ConnPool
	u.SelectedModes.db = db.Session(&gorm.Session{Initialized: true})
	u.SelectedModes.db.Statement.ConnPool = db.Statement.ConnPool
	u.Pins.db = db.Session(&gorm.Session{Initialized: true})
	u.Pins.db.Statement.ConnPool = db.Statement.ConnPool
	return u
}

func (u user) replaceDB(db *gorm.DB) user {
	u.userDo.ReplaceDB(db)
	u.Messages.db = db.Session(&gorm.Session{})
	u.Donations.db = db.Session(&gorm.Session{})
	u.CreatedModes.db = db.Session(&gorm.Session{})
	u.SelectedModes.db = db.Session(&gorm.Session{})
	u.Pins.db = db.Session(&gorm.Session{})
	return u
}

type userHasManyMessages struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
		Messages struct {
			field.RelationField
		}
		Donations struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}
		CreatedModes struct {
			field.RelationField
			Creator struct {
				field.RelationField
			}
			SelectedModes struct {
				field.RelationField
				Mode struct {
					field.RelationField
				}
				User struct {
					field.RelationField
				}
			}
		}
		SelectedModes struct {
			field.RelationField
		}
		Pins struct {
			field.RelationField
			User struct {
				field.RelationField
			}
		}
	}
}

func (a userHasManyMessages) Where(conds ...field.Expr) *userHasManyMessages {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasManyMessages) WithContext(ctx context.Context) *userHasManyMessages {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasManyMessages) Session(session *gorm.Session) *userHasManyMessages {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasManyMessages) Model(m *entities.User) *userHasManyMessagesTx {
	return &userHasManyMessagesTx{a.db.Model(m).Association(a.Name())}
}

func (a userHasManyMessages) Unscoped() *userHasManyMessages {
	a.db = a.db.Unscoped()
	return &a
}

type userHasManyMessagesTx struct{ tx *gorm.Association }

func (a userHasManyMessagesTx) Find() (result []*entities.Message, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasManyMessagesTx) Append(values ...*entities.Message) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasManyMessagesTx) Replace(values ...*entities.Message) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasManyMessagesTx) Delete(values ...*entities.Message) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasManyMessagesTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasManyMessagesTx) Count() int64 {
	return a.tx.Count()
}

func (a userHasManyMessagesTx) Unscoped() *userHasManyMessagesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userHasManyDonations struct {
	db *gorm.DB

	field.RelationField
}

func (a userHasManyDonations) Where(conds ...field.Expr) *userHasManyDonations {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasManyDonations) WithContext(ctx context.Context) *userHasManyDonations {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasManyDonations) Session(session *gorm.Session) *userHasManyDonations {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasManyDonations) Model(m *entities.User) *userHasManyDonationsTx {
	return &userHasManyDonationsTx{a.db.Model(m).Association(a.Name())}
}

func (a userHasManyDonations) Unscoped() *userHasManyDonations {
	a.db = a.db.Unscoped()
	return &a
}

type userHasManyDonationsTx struct{ tx *gorm.Association }

func (a userHasManyDonationsTx) Find() (result []*entities.Donation, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasManyDonationsTx) Append(values ...*entities.Donation) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasManyDonationsTx) Replace(values ...*entities.Donation) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasManyDonationsTx) Delete(values ...*entities.Donation) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasManyDonationsTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasManyDonationsTx) Count() int64 {
	return a.tx.Count()
}

func (a userHasManyDonationsTx) Unscoped() *userHasManyDonationsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userHasManyCreatedModes struct {
	db *gorm.DB

	field.RelationField
}

func (a userHasManyCreatedModes) Where(conds ...field.Expr) *userHasManyCreatedModes {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasManyCreatedModes) WithContext(ctx context.Context) *userHasManyCreatedModes {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasManyCreatedModes) Session(session *gorm.Session) *userHasManyCreatedModes {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasManyCreatedModes) Model(m *entities.User) *userHasManyCreatedModesTx {
	return &userHasManyCreatedModesTx{a.db.Model(m).Association(a.Name())}
}

func (a userHasManyCreatedModes) Unscoped() *userHasManyCreatedModes {
	a.db = a.db.Unscoped()
	return &a
}

type userHasManyCreatedModesTx struct{ tx *gorm.Association }

func (a userHasManyCreatedModesTx) Find() (result []*entities.Mode, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasManyCreatedModesTx) Append(values ...*entities.Mode) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasManyCreatedModesTx) Replace(values ...*entities.Mode) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasManyCreatedModesTx) Delete(values ...*entities.Mode) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasManyCreatedModesTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasManyCreatedModesTx) Count() int64 {
	return a.tx.Count()
}

func (a userHasManyCreatedModesTx) Unscoped() *userHasManyCreatedModesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userHasManySelectedModes struct {
	db *gorm.DB

	field.RelationField
}

func (a userHasManySelectedModes) Where(conds ...field.Expr) *userHasManySelectedModes {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasManySelectedModes) WithContext(ctx context.Context) *userHasManySelectedModes {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasManySelectedModes) Session(session *gorm.Session) *userHasManySelectedModes {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasManySelectedModes) Model(m *entities.User) *userHasManySelectedModesTx {
	return &userHasManySelectedModesTx{a.db.Model(m).Association(a.Name())}
}

func (a userHasManySelectedModes) Unscoped() *userHasManySelectedModes {
	a.db = a.db.Unscoped()
	return &a
}

type userHasManySelectedModesTx struct{ tx *gorm.Association }

func (a userHasManySelectedModesTx) Find() (result []*entities.SelectedMode, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasManySelectedModesTx) Append(values ...*entities.SelectedMode) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasManySelectedModesTx) Replace(values ...*entities.SelectedMode) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasManySelectedModesTx) Delete(values ...*entities.SelectedMode) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasManySelectedModesTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasManySelectedModesTx) Count() int64 {
	return a.tx.Count()
}

func (a userHasManySelectedModesTx) Unscoped() *userHasManySelectedModesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userHasManyPins struct {
	db *gorm.DB

	field.RelationField
}

func (a userHasManyPins) Where(conds ...field.Expr) *userHasManyPins {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasManyPins) WithContext(ctx context.Context) *userHasManyPins {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasManyPins) Session(session *gorm.Session) *userHasManyPins {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasManyPins) Model(m *entities.User) *userHasManyPinsTx {
	return &userHasManyPinsTx{a.db.Model(m).Association(a.Name())}
}

func (a userHasManyPins) Unscoped() *userHasManyPins {
	a.db = a.db.Unscoped()
	return &a
}

type userHasManyPinsTx struct{ tx *gorm.Association }

func (a userHasManyPinsTx) Find() (result []*entities.Pin, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasManyPinsTx) Append(values ...*entities.Pin) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasManyPinsTx) Replace(values ...*entities.Pin) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasManyPinsTx) Delete(values ...*entities.Pin) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasManyPinsTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasManyPinsTx) Count() int64 {
	return a.tx.Count()
}

func (a userHasManyPinsTx) Unscoped() *userHasManyPinsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userDo struct{ gen.DO }

type IUserDo interface {
	gen.SubQuery
	Debug() IUserDo
	WithContext(ctx context.Context) IUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserDo
	WriteDB() IUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserDo
	Not(conds ...gen.Condition) IUserDo
	Or(conds ...gen.Condition) IUserDo
	Select(conds ...field.Expr) IUserDo
	Where(conds ...gen.Condition) IUserDo
	Order(conds ...field.Expr) IUserDo
	Distinct(cols ...field.Expr) IUserDo
	Omit(cols ...field.Expr) IUserDo
	Join(table schema.Tabler, on ...field.Expr) IUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserDo
	Group(cols ...field.Expr) IUserDo
	Having(conds ...gen.Condition) IUserDo
	Limit(limit int) IUserDo
	Offset(offset int) IUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserDo
	Unscoped() IUserDo
	Create(values ...*entities.User) error
	CreateInBatches(values []*entities.User, batchSize int) error
	Save(values ...*entities.User) error
	First() (*entities.User, error)
	Take() (*entities.User, error)
	Last() (*entities.User, error)
	Find() ([]*entities.User, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entities.User, err error)
	FindInBatches(result *[]*entities.User, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*entities.User) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserDo
	Assign(attrs ...field.AssignExpr) IUserDo
	Joins(fields ...field.RelationField) IUserDo
	Preload(fields ...field.RelationField) IUserDo
	FirstOrInit() (*entities.User, error)
	FirstOrCreate() (*entities.User, error)
	FindByPage(offset int, limit int) (result []*entities.User, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userDo) Debug() IUserDo {
	return u.withDO(u.DO.Debug())
}

func (u userDo) WithContext(ctx context.Context) IUserDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userDo) ReadDB() IUserDo {
	return u.Clauses(dbresolver.Read)
}

func (u userDo) WriteDB() IUserDo {
	return u.Clauses(dbresolver.Write)
}

func (u userDo) Session(config *gorm.Session) IUserDo {
	return u.withDO(u.DO.Session(config))
}

func (u userDo) Clauses(conds ...clause.Expression) IUserDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userDo) Returning(value interface{}, columns ...string) IUserDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userDo) Not(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userDo) Or(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userDo) Select(conds ...field.Expr) IUserDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userDo) Where(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userDo) Order(conds ...field.Expr) IUserDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userDo) Distinct(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userDo) Omit(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userDo) Join(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userDo) Group(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userDo) Having(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userDo) Limit(limit int) IUserDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userDo) Offset(offset int) IUserDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userDo) Unscoped() IUserDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userDo) Create(values ...*entities.User) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userDo) CreateInBatches(values []*entities.User, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userDo) Save(values ...*entities.User) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userDo) First() (*entities.User, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entities.User), nil
	}
}

func (u userDo) Take() (*entities.User, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entities.User), nil
	}
}

func (u userDo) Last() (*entities.User, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entities.User), nil
	}
}

func (u userDo) Find() ([]*entities.User, error) {
	result, err := u.DO.Find()
	return result.([]*entities.User), err
}

func (u userDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entities.User, err error) {
	buf := make([]*entities.User, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userDo) FindInBatches(result *[]*entities.User, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userDo) Attrs(attrs ...field.AssignExpr) IUserDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userDo) Assign(attrs ...field.AssignExpr) IUserDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userDo) Joins(fields ...field.RelationField) IUserDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userDo) Preload(fields ...field.RelationField) IUserDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userDo) FirstOrInit() (*entities.User, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entities.User), nil
	}
}

func (u userDo) FirstOrCreate() (*entities.User, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entities.User), nil
	}
}

func (u userDo) FindByPage(offset int, limit int) (result []*entities.User, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userDo) Delete(models ...*entities.User) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userDo) withDO(do gen.Dao) *userDo {
	u.DO = *do.(*gen.DO)
	return u
}
